### ISSUE TITLE
Desain figma

### ISSUE THREAD

**Issue by ditanursabila** [magical-teams/face-presensi#5]

**Comment by salmatsaniatul** [comment]
Dokumentasi Desain Figma
 Desain Figma :
https://www.figma.com/design/kYMknU6fuQc9mR8mzMNJEi/face-presensi?node-id=0-1&t=5dH149m8KdEWzYiT-1
Kode Warna :
[SALMA TSANIATUL MUNAWAROH - 2 DESIGN.pdf](https://github.com/user-attachments/files/17005130/SALMA.TSANIATUL.MUNAWAROH.-.2.DESIGN.pdf)

**Comment by ditanursabila** [comment]
Pada Min, 15 Sep 2024 pukul 15.55 salmatsaniatul ***@***.***>
menulis:
